on: push
name: cibuild

permissions:
  contents: read

jobs:
  build:
    name: Test
    strategy:
      matrix:
        ruby: [2.6, 2.7]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: script/cibuild
        run: script/cibuild
