on: push
name: cibuild

permissions:
  contents: read

jobs:
  build:
    name: Test
    strategy:
      matrix:
        ruby: [2.6, 2.7]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1.306.0
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: script/cibuild
        run: script/cibuild
